import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { loadCurrentUser } from "@/features/auth/server/load-current-user";
import { CurrentUserProvider } from "@/features/auth/context/current-user-context";
import { Footer } from "@/components/common/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await loadCurrentUser();

  return (
    <html lang="ko" suppressHydrationWarning>
      <body className="antialiased font-sans flex flex-col min-h-screen">
        <Providers>
          <CurrentUserProvider initialState={currentUser}>
            <div className="flex-1">
              {children}
            </div>
            <Footer />
          </CurrentUserProvider>
        </Providers>
      </body>
    </html>
  );
}
